"""Repair a corrupt public data pack using the owner's supplied INF.2213.00.
Source: eight rendered pages of 'INF.2213 Guia de Reconstituição, Diluição e
Administração de Antibióticos.pdf', footer 'Versão vigente à data 28-08-2026'.
This is a transcription, not a clinical validation or a current formulary.
Merged dosage/route cells are repeated explicitly. A dash stays unspecified.
"""
import json
from pathlib import Path
ROWS=[]
READY='Não é necessária reconstituição (solução pronta)'
NONE='Não é necessária diluição'
UNSPEC='Não especificada no documento (—).'
def add(page,drug,dose,form,obs,variants):
    for route,recon,rs,dil,ds in variants:
        ROWS.append(dict(id=f'inf2213-{len(ROWS)+1:03}',page=page,drug=drug,dose=dose,form=form,route=route,reconstitution=recon,reconstitution_stability=rs,dilution=dil,dilution_stability=ds,observations=obs,source_code='INF.2213.00',source_page=page,transcription_date='2026-09-16'))
obs='A amicacina é nefrotóxica, ototóxica e neurotóxica. Incompatível com outro antibiótico beta-lactâmico. Não associar outros medicamentos na solução. A coloração pálida não implica perda de potência.'
add(1,'Amicacina','500 mg/2 mL','Solução injetável',obs,[('IV perfusão (30–60 minutos)',READY,'','CF = 0,25–5 mg/mL; solventes: SF ou SG 5%','TA: 24 horas (Hikma)'),('IM',READY,'',NONE,'')])
obs='Não administrar por via intramuscular. Incompatível com derivados do sangue, fluídos proteicos, tais como hidrolisados de proteínas ou emulsões de lípidos, e com soluções que contenham glucose, dextrano ou bicarbonato. Após a reconstituição, a solução apresenta uma cor amarelo pálido. As soluções que apresentem partículas em suspensão devem ser rejeitadas.'
add(1,'Amoxicilina + Ácido clavulânico','2000 mg + 200 mg','Pó para solução para perfusão',obs,[('IV perfusão (30–40 minutos)','20 mL de a.p.i.','TA: 20 minutos (Hikma)','≥ 100 mL de a.p.i. ou SF','TA: 1 hora (Hikma)')])
add(1,'Amoxicilina + Ácido clavulânico','1000 mg + 200 mg','Pó para solução injetável',obs,[('IV bólus (3–4 minutos)','20 mL de a.p.i.','TA: 20 minutos (Hikma)',NONE,''),('IV perfusão (30–40 minutos)','20 mL de a.p.i.','TA: 20 minutos (Hikma)','≥ 100 mL de a.p.i. ou SF','TA: 1 hora (Hikma)')])
add(1,'Amoxicilina + Ácido clavulânico','500 mg/10 mL + 50 mg/10 mL','Pó e solvente para solução injetável',obs,[('IV bólus (3–4 minutos)','10 mL de a.p.i.','Administrar de imediato (Atral)',NONE,''),('IV perfusão (30–40 minutos)','10 mL de a.p.i.','Diluir de imediato (Atral)','50 mL de SF','TA: 1 hora (Atral)')])
obs='A administração IV bólus deve ser lenta para evitar convulsões. Incompatível com aminoglicosídeos. Na preparação deve-se utilizar preferencialmente agulhas com diâmetro externo inferior ou igual a 0,8 mm, isto é, de calibre superior ou igual a 21G.'
add(1,'Ampicilina','1000 mg','Pó para solução injetável',obs,[('IV perfusão (60 minutos)','3 mL de a.p.i.','TA: 1 hora (Labesfal)','CF ≤ 30 mg/mL; solvente: SF','TA: 4 horas; frigorífico: 24 horas (Labesfal)'),('IM','3 mL de a.p.i.','TA: 1 hora (Labesfal)',NONE,'')])
add(1,'Ampicilina','500 mg / 250 mg (apresentações indicadas na mesma célula do guia)','Pó para solução injetável',obs,[('IV bólus (10–15 minutos)','5 mL de a.p.i.','TA: 1 hora (Atral)',NONE,''),('IV perfusão (60 minutos)','5 mL de a.p.i.','TA: 1 hora (Atral)','CF ≤ 30 mg/mL; solvente: SF','TA: 8–10 horas; frigorífico: 72 horas (Atral)'),('IM','2 mL de a.p.i.','TA: 1 hora (Atral)',NONE,'')])
obs='As soluções que apresentem partículas em suspensão devem ser rejeitadas. Não associar outros medicamentos, aditivos ou outras substâncias intravenosas na solução.'
add(2,'Azitromicina','500 mg','Pó para solução para perfusão',obs,[('IV perfusão (60 minutos para 2 mg/mL; 180 minutos para 1 mg/mL)','4,8 mL de a.p.i.','Frigorífico: 24 horas (Farmoz)','CF = 1–2 mg/mL; solventes: SG 5% ou SF','Frigorífico: 24 horas (Farmoz)')])
obs='Administrar apenas por via intramuscular. A agulha deverá ter um diâmetro interno de 0,8 mm. Na ausência de estudos de compatibilidade, não associar com outros medicamentos.'
add(2,'Benzilpenicilina benzatínica','1 200 000 UI/4 mL','Pó e veículo para suspensão injetável',obs,[('IM','4 mL de solvente (a.p.i. + CL)','Administrar de imediato (Atral)',NONE,'')])
add(2,'Benzilpenicilina benzatínica + benzilpenicilina potássica + benzilpenicilina procaínica','600 000 UI + 300 000 UI + 300 000 UI','Pó e veículo para suspensão injetável',obs,[('IM','4 mL de solvente (a.p.i. + CL)','Administrar de imediato (Atral)',NONE,'')])
obs='A injeção na proximidade de nervos periféricos ou vasos sanguíneos principais pode produzir danos neurovasculares. Na administração por via intramuscular, são bem toleradas as soluções com concentrações até 100 000 UI/mL. A benzilpenicilina potássica pode também ser administrada por IV perfusão intermitente: administrar 1/6 ou 1/4 da dose diária total através de uma perfusão durante 1–2 horas, a cada 4 ou 6 horas, respetivamente. Não associar outros medicamentos na solução.'
add(2,'Benzilpenicilina sódica e potássica','1 000 000 UI','Pó para solução injetável',obs,[('IM','10 mL de a.p.i. ou SF (100 000 UI/mL)','TA: 24 horas; frigorífico: 72 horas (Atral)',NONE,''),('Perfusão contínua (24 horas)','10 mL de a.p.i. ou SF (100 000 UI/mL)','TA: 24 horas; frigorífico: 72 horas (Atral)','1000–2000 mL de a.p.i. ou SF','TA: 24 horas; frigorífico: 72 horas (Atral)')])
obs='As soluções que apresentem partículas em suspensão devem ser rejeitadas. Após a reconstituição, as soluções de cefazolina devem ser protegidas da luz. A cor das soluções varia de amarelo pálido a amarelo.'
add(2,'Cefazolina','1000 mg/10 mL','Pó e solvente para solução injetável',obs,[('IV bólus (3–5 minutos)','10 mL de a.p.i.','TA: 24 horas (Hikma)',NONE,''),('IV perfusão (15–60 minutos)','10 mL de a.p.i.','TA: 24 horas (Hikma)','50–100 mL de SF ou SG 5%','TA: 24 horas; frigorífico: 96 horas (Hikma)')])
obs='Incompatível com soluto de bicarbonato de sódio. Precaução nos doentes com restrição de sódio, devido à percentagem de sódio contida.'
add(3,'Cefotaxima','1000 mg/4 mL','Pó e solvente para solução injetável',obs,[('IV bólus (3–5 minutos)','4 mL de a.p.i.','TA: 24 horas (Labesfal)',NONE,''),('IV perfusão (50–60 minutos)','4 mL de a.p.i.','TA: 24 horas (Labesfal)','96 mL de SF ou SG 5%',UNSPEC),('IM','4 mL de a.p.i. ou CL a 1%','TA: 24 horas (Labesfal)',NONE,'')])
obs='A solução de lidocaína nunca deve ser administrada por via intravenosa. A cor do pó e das soluções pode variar de amarelo pálido a âmbar sem afetar a eficácia. As soluções que apresentem partículas em suspensão devem ser rejeitadas.'
add(3,'Cefoxitina','1000 mg/10 mL','Pó e solvente para solução injetável',obs,[('IV bólus (3–5 minutos)','10 mL de a.p.i.','TA: 24 horas (Hikma)',NONE,''),('IV perfusão (15–60 minutos)','10 mL de a.p.i.','TA: 24 horas (Hikma)','50–100 mL de SF, SG 5% ou a.p.i.',UNSPEC),('IM','2 mL de a.p.i. ou CL a 0,5% ou 1%','TA: 24 horas (Hikma)',NONE,'')])
obs='A administração intravenosa é a preferencial. Incompatível com aminoglicosídeos e vancomicina. Não associar outros medicamentos na solução. As pequenas bolhas na solução reconstituída podem ser ignoradas. A cor da solução pode variar de ligeiramente amarelada até âmbar sem afetar a potência. Recomenda-se como local de injeção intramuscular o quadrante superior externo do grande glúteo ou a parte lateral da coxa.'
add(3,'Ceftazidima','1000 mg','Pó para solução injetável ou para perfusão',obs,[('IV bólus (< 5 minutos)','10 mL de SF ou SF + SG 5%','Administrar de imediato (Hikma)',NONE,''),('IV perfusão (15–30 minutos)','10 mL de SF ou SF + SG 5%','Diluir de imediato (Hikma)','≥ 40 mL de SF ou SF + SG 5%','Administrar de imediato'),('IM','3 mL de CL a 0,5% ou a 1%','Administrar de imediato (Hikma)',NONE,'')])
obs='As doses intravenosas de 50 mg/kg ou superiores em bebés e crianças até aos 12 anos de idade devem ser administradas por perfusão. Incompatível com amsacrina, vancomicina, fluconazol, aminoglicosídeos e labetalol. Não associar com soluções que contenham cálcio, incluindo nutrição parentérica total, nem com qualquer fármaco à exceção do cloridrato de lidocaína a 1%. As soluções que apresentem partículas em suspensão devem ser rejeitadas.'
s='TA: 12 horas; frigorífico: 48 horas (Fresenius Kabi)'
add(3,'Ceftriaxona','1000 mg','Pó para solução injetável ou para perfusão',obs,[('IV bólus (5 minutos)','10 mL de a.p.i.',s,NONE,''),('IV perfusão (≥ 30 minutos; 60 minutos em recém-nascidos)','10 mL de SF ou SG 5%',s,'10 mL de SF ou SG 5%',s),('IM','3 mL de CL a 1%',s,NONE,'')])
obs='Incompatível com antibióticos aminoglicosídeos. Pode verificar-se um certo escurecimento da suspensão preparada durante o armazenamento.'
s='TA: 5 horas; frigorífico: 48 horas (Labesfal)'
add(4,'Cefuroxima','750 mg','Pó e solvente para solução injetável',obs,[('IV bólus (3–5 minutos)','≥ 6 mL de a.p.i.',s,NONE,''),('IV perfusão (30–60 minutos)','50–100 mL de a.p.i.','TA: 24 horas; frigorífico: 72 horas (Labesfal)',NONE,''),('IM','3 mL de a.p.i.',s,NONE,'')])
add(4,'Ciprofloxacina','200 mg/100 mL','Solução para perfusão','Na ausência de estudos de compatibilidade, não associar outros medicamentos na solução. Não colocar no frigorífico. As soluções que apresentem cristais em suspensão devem ser rejeitadas.',[('IV perfusão (60 minutos em crianças; 30 minutos em adultos)',READY,'','Diluição opcional; solventes: SF ou SG 5%','')])
add(4,'Claritromicina','500 mg','Pó para solução para perfusão','Não associar outros medicamentos na solução, sem que a estabilidade tenha sido previamente determinada. As soluções que apresentem partículas em suspensão devem ser rejeitadas.',[('IV perfusão (60 minutos)','10 mL de a.p.i.','TA: 24 horas; frigorífico: 48 horas (Hikma)','≥ 250 mL de SG 5% ou SF','TA: 6 horas; frigorífico: 48 horas (Hikma)')])
obs='Incompatível com ampicilina, difenil-hidantoína sódica, barbitúricos, aminofilina, gluconato de cálcio e sulfato de magnésio. Compatível com sulfato de amicacina, aztreonam, nafato de cefamandole, cefazolina sódica, cefotaxima sódica, cefoxitina sódica, ceftazidima sódica, ceftizoxima sódica, sulfato de gentamicina, sulfato de netilmicina, piperacilina e tobramicina.'
add(4,'Clindamicina','600 mg/4 mL','Solução injetável',obs,[('IV perfusão (10–60 minutos)',READY,'','50–100 mL de SG 5% ou SF','TA: 16 dias; frigorífico: 32 dias (Labesfal)'),('IM',READY,'',NONE,'')])
add(5,'Colistina','1 000 000 UI','Pó para solução injetável','Incompatível com eritromicina, tetraciclina e cefalotina.',[('IV bólus (≥ 5 minutos)','≤ 10 mL de a.p.i. ou SF','Frigorífico: 24 horas (Accord Healthcare)',NONE,''),('IV perfusão (30–60 minutos)','≤ 10 mL de a.p.i. ou SF','Frigorífico: 24 horas (Accord Healthcare)','Diluição opcional com 50 mL de SF','Administrar de imediato (Accord Healthcare)')])
add(5,'Cotrimoxazol','480 mg/5 mL','Solução injetável','Verificar a ocorrência de formação de precipitado antes e durante a perfusão.',[('IV perfusão (60–90 minutos)',READY,'','125 mL de SF ou SG 5%','TA: 48 horas (Ratiopharm)')])
obs='A a.p.i. não deve ser usada para a reconstituição caso a solução seja administrada por IV bólus. O produto liofilizado demora cerca de 15 minutos para se dissolver. Incompatível com soluções de glucose. Não associar outros medicamentos na solução, exceto aztreonam, ceftazidima, ceftriaxona, gentamicina, fluconazol, levofloxacina, dopamina, heparina e lidocaína. A cor da solução reconstituída varia entre amarelo pálido e castanho claro.'
add(5,'Daptomicina','500 mg','Pó para solução injetável ou para perfusão',obs,[('IV bólus (apenas em adultos; 2 minutos)','10 mL de SF','TA: 12 horas; frigorífico: 48 horas (Merck)',NONE,''),('IV perfusão (30 minutos em doentes com ≥ 7 anos; 60 minutos em doentes com < 7 anos)','10 mL de SF','TA: 12 horas; frigorífico: 48 horas (Merck)','50 mL de SF','TA: 12 horas; frigorífico: 24 horas (Merck)')])
obs='A perfusão contínua é preferível à perfusão descontínua, no entanto se se utilizar a perfusão descontínua em intervalos inferiores de 6 horas esta também é efetiva. Incompatível com solventes que contenham conservantes ou sais inorgânicos. A solução reconstituída deve ser límpida e isenta de partículas em suspensão.'
add(5,'Eritromicina','1000 mg','Pó para solução injetável',obs,[('IV perfusão (20–60 minutos)','20 mL de a.p.i.','TA: 24 horas; frigorífico: 48 horas (Labesfal)','CF = 1 a 5 mg/mL; solvente: SF','TA: 12 horas (Labesfal)'),('Perfusão contínua (24 horas)','20 mL de a.p.i.','TA: 24 horas; frigorífico: 48 horas (Labesfal)','CF = 1 mg/mL; solvente: SF','TA: 12 horas (Labesfal)')])
add(6,'Ertapenem','1000 mg','Pó para concentrado para solução para perfusão','Incompatível com solventes que contenham dextrose. Não associar com outros medicamentos na solução, exceto heparina sódica e cloreto de potássio. Utilizar num prazo de 4 horas após retirar do frigorífico. As soluções oscilam de incolores a amarelo pálido sem que a potência seja afetada.',[('IV perfusão (30 minutos)','10 mL de a.p.i. ou SF','Diluir de imediato (Merck)','> 12 anos: 50 mL de SF; ≤ 12 anos: CF ≤ 20 mg/mL, solvente: SF','TA: 6 horas; frigorífico: 24 horas (Merck)')])
obs='Incompatível com sangue, emulsões lipídicas intravenosas, hidrolisados de proteínas ou outros líquidos contendo proteínas. Não associar outros medicamentos na solução.'
s='TA: 30 minutos; frigorífico: 24 horas (Labesfal)'
add(6,'Flucloxacilina','500 mg/2 mL','Pó e solvente para solução injetável',obs,[('IV bólus (3–5 minutos)','10–20 mL de a.p.i. ou SF',s,NONE,''),('IV perfusão (20–30 minutos)','10 mL de a.p.i. ou SF',s,'CF = 1%; solventes: a.p.i. ou SF ou SG 5%','Frigorífico: 24 horas (Labesfal)'),('IM','2 mL de a.p.i.',s,NONE,'')])
add(6,'Levofloxacina','500 mg/100 mL','Solução para perfusão','Incompatível com heparina ou soluções alcalinas. Na ausência de estudos de compatibilidade, não associar outros medicamentos na solução. Após reconstituição a solução é límpida, com coloração amarelo-esverdeada e sem partículas visíveis.',[('IV perfusão (60 minutos)',READY,'',NONE+' (solução pronta)','')])
add(6,'Linezolida','600 mg/300 mL','Solução para perfusão','Incompatível com anfotericina B, cloridrato de cloropromazina, diazepam, isotionato de pentamidina, lactobionato de eritromicina, fenitoína sódica, cotrimoxazol e ceftriaxona sódica. Não introduzir aditivos na solução. Na ausência de estudos de compatibilidade, não associar outros medicamentos na solução.',[('IV perfusão (30–120 minutos)',READY,'',NONE+' (solução pronta)','')])
obs='Não associar outros medicamentos na solução. As soluções reconstituídas não devem ser congeladas. A solução deve ser agitada antes de utilizar.'
for dose in ['1000 mg','500 mg']:
    add(7,'Meropenem',dose,'Pó para solução injetável ou para perfusão',obs,[('IV bólus (até doses de 20 mg/kg; 5 minutos)','CF = 50 mg/mL; solvente: a.p.i.','TA: 3 horas; frigorífico: 12 horas (Hikma)',NONE,''),('IV perfusão (15–30 minutos)','CF = 1–20 mg/mL; solventes: SF ou SG 5%','TA: 3 horas (SF) / 1 hora (SG 5%); frigorífico: 24 horas (SF) (Hikma)',NONE,'')])
add(7,'Metronidazol','500 mg/100 mL','Solução para perfusão','Compatível com solução isotónica de cloreto de sódio para perfusão, solução isotónica de glucose para perfusão ou solução de Ringer para perfusão. Não associar com outras soluções de perfusão nem com outros medicamentos.',[('IV perfusão (100 mL em 20–30 minutos; 200 mL em 40–60 minutos)',READY,'',NONE+' (solução pronta)','')])
obs='Incompatível com soluções que contenham bicarbonato de sódio, solução de lactato de Ringer, sangue ou hidrolisados da albumina. Não associar outros medicamentos na solução.'
add(7,'Piperacilina + Tazobactam','4 + 0,5 g','Pó para solução para perfusão',obs,[('IV perfusão (30 minutos)','20 mL de a.p.i. ou SF','TA: 12 horas; frigorífico: 48 horas (Hikma)','100 mL de SF ou SG 5%','TA: 12 horas; frigorífico: 48 horas (Hikma)')])
add(7,'Piperacilina + Tazobactam','2 + 0,25 g','Pó para solução para perfusão',obs,[('IV perfusão (30 minutos)','10 mL de a.p.i. ou SF','Frigorífico: 24 horas (Fresenius Kabi)','100 mL de SF ou SG 5%','Frigorífico: 24 horas (Fresenius Kabi)')])
add(7,'Rifampicina','600 mg','Pó e solvente para solução para perfusão','Durante a reconstituição, agitar o frasco vigorosa e continuamente por aproximadamente 30 segundos. Quando o pó estiver completamente dissolvido e a espuma tiver desaparecido, deve-se proceder para a diluição. Não associar outros medicamentos na solução.',[('IV perfusão (2–3 horas)','10 mL de a.p.i.','TA: 6 horas (Sanofi)','500 mL de SG 5% ou SF','TA: 6 horas (Sanofi)')])
obs='Incompatível com aminoglicosídeos. Não associar outros medicamentos na solução. Se a solução reconstituída contiver espuma, deve-se deixá-la repousar durante 15 minutos. Após reconstituição a solução é límpida, transparente de cor ligeiramente acastanhada. A estabilidade da solução diluída de teicoplanina com solução de glucose a 5% é menor, devendo ser administrada de imediato.'
s='Frigorífico: 24 horas (Sidefarma)'
add(8,'Teicoplanina','200 mg/3 mL','Pó e solvente para solução injetável ou para perfusão',obs,[('IV bólus (3–5 minutos)','3 mL de a.p.i.',s,NONE,''),('IV perfusão (apenas em recém-nascidos, conforme redação do documento; 30 minutos)','3 mL de a.p.i.',s,'100 mL de SF (preferível) ou SG 5%',s),('IM','3 mL de a.p.i.',s,NONE,'')])
obs='Incompatível com anfotericina B, anfotericina B complexo lipídico, diazepam, esomeprazol, omeprazol e soluções intravenosas que podem resultar num aumento de pH acima de 7. Não associar outros medicamentos na solução, exceto amicacina, dobutamina, cloridrato de dopamina, cloridrato de lidocaína, gentamicina, haloperidol, lactato de Ringer, metoclopramida, morfina, noradrenalina, piperacilina/tazobactam (formulação com EDTA), cloreto de potássio, propofol, cloridrato de ranitidina, teofilina e tobramicina. A solução reconstituída deve ser amarelo-alaranjada.'
add(8,'Tigeciclina','50 mg','Pó para solução para perfusão',obs,[('IV perfusão (30–60 minutos)','5,3 mL de SF ou SG 5%','Diluir de imediato (Pfizer)','Retirar 5 mL da solução reconstituída e adicionar 100 mL de SF ou SG 5%','Administrar de imediato (Pfizer)')])
obs='A perfusão contínua apenas deverá ser utilizada quando o tratamento com perfusão intermitente não é possível. A concentração máxima de vancomicina que é recomendada para perfusão é de 5 mg/mL. Não associar outros medicamentos na solução. Antes da administração, verificar se ocorreu precipitação ou alteração da cor da solução. Após reconstituição a solução deve ser límpida, incolor a ligeiramente amarelo-acastanhada e sem partículas visíveis. Após diluição a solução deve ser límpida, incolor e sem partículas visíveis.'
s='TA: 48 horas; frigorífico: 48 horas (Hikma)'
add(8,'Vancomicina','1000 mg','Pó para concentrado para solução para perfusão',obs,[('IV perfusão (via preferencial; 120 minutos)','20 mL de a.p.i.','Diluir de imediato (Hikma)','CF ≤ 5 mg/mL; solventes: SF ou SG 5%',s)])
add(8,'Vancomicina','500 mg / 1000 mg (apresentações abrangidas pela linha de perfusão contínua)','Pó para concentrado para solução para perfusão',obs,[('Perfusão contínua (24 horas)','10 mL de a.p.i. (500 mg); 20 mL de a.p.i. (1000 mg)','Diluir de imediato (Hikma)','Diluir 1000–2000 mg de vancomicina dissolvida em 250–500 mL de SF ou SG 5%',s)])
add(8,'Vancomicina','500 mg','Pó para concentrado para solução para perfusão',obs,[('IV perfusão (via preferencial; 60 minutos)','10 mL de a.p.i.','Diluir de imediato (Hikma)','CF ≤ 5 mg/mL; solventes: SF ou SG 5%',s)])
assert len(ROWS)==66, len(ROWS)
assert len({r['drug'] for r in ROWS})==31
DATA={'source':{'code':'INF.2213.00','title':'Guia de Reconstituição, Diluição e Administração de Antibióticos','pages':8,'vigente':'28-08-2026','recoveredAt':'2026-09-16','method':'Transcrição das oito páginas renderizadas do documento fornecido pelo proprietário; não é revalidação clínica.','legend':'a.p.i.: água para injetáveis; SF: cloreto de sódio 0,9%; SG 5%: solução de glucose 5%; CL: cloridrato de lidocaína; TA: ≤25 °C; frigorífico: 2–8 °C.','limitations':['A estabilidade do documento não garante condições microbiológicas após manipulação.','Conservar as condições de apresentação, fabricante e via; não generalizar entre produtos.','A redação da teicoplanina e os volumes da ceftriaxona são transcritos sem alteração: precisam de revisão clínica frente ao RCM e protocolo vigente antes de utilização assistencial.']},'records':ROWS}
OUT=Path(__file__).resolve().parents[1]/'data'/'antibiotics-recovered.json'
OUT.parent.mkdir(exist_ok=True);OUT.write_text(json.dumps(DATA,ensure_ascii=False,separators=(',',':')))
print(f'Antibiotic transcription: {len(ROWS)} route/presentation rows; {len({r["drug"] for r in ROWS})} names; 8 pages')
